In [1]:
import pandas as pd

In [2]:
import plotly.express as px

In [3]:
kkkfull = pd.read_csv('kkk-ledgers-index.csv', low_memory=False)
dtype={'user_id': int}

In [4]:
pd.options.display.max_columns=50

In [5]:
kkkfull

,itemID,Number,fullName,Prefix,Last Name,First Name,Middle Name,Suffix,residenceAddress1,residenceAddress2,Residence Address,Residence Other,residenceCity,residenceState,Residence City & State,residencePhone,businessAddress1,businessAddress2,Business Address,Business Other,businessCity,businessState,Business City & State,businessPhone,ledger,link,Ledger Link,Page,pdfFileName,symbolExists,sNumber,sErased,Notes & Remarks,Column 29
0,K00001,12.0,Fred H Crass,NaN,Crass,Fred,H,NaN,219 E Maple,NaN,219 E Maple,NaN,Denver,CO*,"Denver, CO*",S2652,1431 15th St.,NaN,1431 15th St.,NaN,Denver,CO*,"Denver, CO*",M5382,MSS.366.5,h-co.org/ledger2,MSS.366.5,3,mss366-5_FC-p74_QC,True,False,False,"""Trans. from old M#636""",NaN
1,K00002,501.0,Harold D Adamson,NaN,Adamson,Harold,D,NaN,NaN,18th & California*,18th & California*,Sears Hotel,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
2,K00003,502.0,J E Adamson,NaN,Adamson,J,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Met State Bank,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,"Name struck; ""NOT N PADONCASE""",NaN
3,K00004,503.0,Albert J Ashade,NaN,Ashade,Albert,J,NaN,2446 Champa,NaN,2446 Champa,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
4,K00005,504.0,Gaylord W Akin,NaN,Akin,Gaylord,W,NaN,1241 Penn,NaN,1241 Penn,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,True,True,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29630,K29638,13778.0,James E McCown,NaN,McCown,James,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.4,h-co.org/ledger1,MSS.366.4,564,mss366-4_p541-BC_QC,False,False,False,NaN,NaN
29631,K29639,13779.0,William F Marlor,NaN,Marlor,William,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.4,h-co.org/ledger1,MSS.366.4,564,mss366-4_p541-BC_QC,False,False,False,NaN,NaN
29632,K29640,13780.0,Albert L Anderson,NaN,Anderson,Albert,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.4,h-co.org/ledger1,MSS.366.4,564,mss366-4_p541-BC_QC,False,False,False,NaN,NaN
29633,K29641,13781.0,Albert H Keeney,NaN,Keeney,Albert,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.4,h-co.org/ledger1,MSS.366.4,564,mss366-4_p541-BC_QC,False,False,False,NaN,NaN
29634,K29642,13782.0,Andrew P Jackson,NaN,Jackson,Andrew,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.4,h-co.org/ledger1,MSS.366.4,564,mss366-4_p541-BC_QC,False,False,False,NaN,NaN

In [6]:
kkkfull.describe(include='all')

,itemID,Number,fullName,Prefix,Last Name,First Name,Middle Name,Suffix,residenceAddress1,residenceAddress2,Residence Address,Residence Other,residenceCity,residenceState,Residence City & State,residencePhone,businessAddress1,businessAddress2,Business Address,Business Other,businessCity,businessState,Business City & State,businessPhone,ledger,link,Ledger Link,Page,pdfFileName,symbolExists,sNumber,sErased,Notes & Remarks,Column 29
count,29635,29633.000000,29635,174,29634,29631,26267,357,14921,433,15334,868,15649,15649,15651,8682,6769,1309,7080,5898,6438,6436,6438,7361,29635,29635,29635,29635.000000,29635,29635,29635,29635,1418,1
unique,29635,NaN,24618,14,8518,1989,1471,12,12965,112,13066,516,169,29,177,7377,4397,63,4441,1845,64,12,66,3434,2,2,2,NaN,20,2,2,2,1075,1
top,K00001,NaN,John W Jones,Dr.,Smith,John,E,Jr.,1376 Pearl,12101 E. Colfax Ave.*,12101 E. Colfax Ave.*,Fitzsimons Hospital,Denver,CO*,"Denver, CO*",AUR800,2145 Blake,17th & Stout*,14th & Larimer*,Denver Tramway,Denver,CO*,"Denver, CO*",M990,MSS.366.5,h-co.org/ledger2,MSS.366.5,NaN,mss366-5_p225-299_QC,False,False,False,Edgewater to Hersey 11/13,"RESIGNED 5-27-26"""
freq,1,NaN,6,123,321,1413,2096,308,10,150,150,136,15004,15172,15003,40,28,201,48,228,6291,6325,6290,221,16737,16737,16737,NaN,1726,22103,24525,29232,20,1
mean,NaN,14596.902946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,333.729374,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,10541.158265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196.832741,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,6711.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,13350.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,328.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,20327.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,489.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,47802.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,741.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
kkkfull.head(20)

,itemID,Number,fullName,Prefix,Last Name,First Name,Middle Name,Suffix,residenceAddress1,residenceAddress2,Residence Address,Residence Other,residenceCity,residenceState,Residence City & State,residencePhone,businessAddress1,businessAddress2,Business Address,Business Other,businessCity,businessState,Business City & State,businessPhone,ledger,link,Ledger Link,Page,pdfFileName,symbolExists,sNumber,sErased,Notes & Remarks,Column 29
0,K00001,12.0,Fred H Crass,NaN,Crass,Fred,H,NaN,219 E Maple,NaN,219 E Maple,NaN,Denver,CO*,"Denver, CO*",S2652,1431 15th St.,NaN,1431 15th St.,NaN,Denver,CO*,"Denver, CO*",M5382,MSS.366.5,h-co.org/ledger2,MSS.366.5,3,mss366-5_FC-p74_QC,True,False,False,"""Trans. from old M#636""",NaN
1,K00002,501.0,Harold D Adamson,NaN,Adamson,Harold,D,NaN,NaN,18th & California*,18th & California*,Sears Hotel,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
2,K00003,502.0,J E Adamson,NaN,Adamson,J,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Met State Bank,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,"Name struck; ""NOT N PADONCASE""",NaN
3,K00004,503.0,Albert J Ashade,NaN,Ashade,Albert,J,NaN,2446 Champa,NaN,2446 Champa,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
4,K00005,504.0,Gaylord W Akin,NaN,Akin,Gaylord,W,NaN,1241 Penn,NaN,1241 Penn,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,True,True,False,NaN,NaN
5,K00006,505.0,J B Alderdice,NaN,Alderdice,J,B,NaN,1760 Penn,NaN,1760 Penn,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
6,K00007,506.0,J M Alexander,NaN,Alexander,J,M,NaN,1017 E 17th St,NaN,1017 E 17th St,Apt. D,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
7,K00008,507.0,B B Aley,NaN,Aley,B,B,NaN,NaN,NaN,NaN,US Nat Bank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
8,K00009,508.0,Dr. Jos H Allen,Dr.,Allen,Jos,H,NaN,435 Majestic Bldg,16th & Broadway*,"435 Majestic Bldg, 16th & Broadway*",Majestic Building*,Denver,CO*,"Denver, CO*",NaN,832 Republic,NaN,832 Republic,NaN,Denver,CO*,"Denver, CO*",NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,True,False,False,NaN,NaN
9,K00010,509.0,C R Alley,NaN,Alley,C,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,620 Syms Bldg.,16th & Champa*,"620 Syms Bldg., 16th & Champa*",Symes Building*,Denver,CO*,"Denver, CO*",NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
10,K00011,510.0,Edw W Almon,NaN,Almon,Edw,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,712 E & C Bldg,17th & Curtis*,"712 E & C Bldg, 17th & Curtis*",Ernest & Cranmer Building*,Denver,CO*,"Denver, CO*",NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,NaN,NaN
11,K00012,511.0,Chas C Anderson,NaN,Anderson,Chas,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1900 Broadway,NaN,1900 Broadway,NaN,Denver,CO*,"Denver, CO*",NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,True,False,False,NaN,NaN
12,K00013,512.0,J A Anderson,NaN,Anderson,J,A,NaN,3052 Wyandotte,NaN,3052 Wyandotte,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
13,K00014,513.0,J H Armstrong,NaN,Armstrong,J,H,NaN,1344 Lincoln,NaN,1344 Lincoln,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
14,K00015,514.0,Ralph J Arnold,NaN,Arnold,Ralph,J,NaN,4966 Irving,NaN,4966 Irving,NaN,Denver,CO*,"Denver, CO*",G918W,402 State Office Bldg,Sherman & Colfax*,"402 State Office Bldg, Sherman & Colfax*",State Office Building*,Denver,CO*,"Denver, CO*",NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,True,False,False,NaN,NaN
15,K00016,515.0,Thos T Arnold,NaN,Arnold,Thos,T,NaN,NaN,NaN,NaN,NaN,Westminster,CO,"Westminster, CO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
16,K00017,516.0,K A Arnwine,NaN,Arnwine,K,A,NaN,303 Cont Trust Bldg,17th & Larimer*,"303 Cont Trust Bldg, 17th & Larimer*",Continental Trust Building*,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
17,K00018,517.0,Gustaf A Askling,NaN,Askling,Gustaf,A,NaN,NaN,NaN,NaN,First National Bank Building*,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,False,False,NaN,NaN
18,K00019,518.0,W L Ayer,NaN,Ayer,W,L,NaN,337 East 17th st,NaN,337 East 17th st,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,True,False,False,NaN,NaN
19,K00020,519.0,Claude M Babb,NaN,Babb,Claude,M,NaN,1748 Williams,NaN,1748 Williams,NaN,Denver,CO*,"Denver, CO*",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSS.366.5,h-co.org/ledger2,MSS.366.5,5,mss366-5_FC-p74_QC,False,True,False,Name struck,NaN

In [8]:
kkkfull.columns

Index(['itemID', 'Number', 'fullName', 'Prefix', 'Last Name', 'First Name',
       'Middle Name', 'Suffix', 'residenceAddress1', 'residenceAddress2',
       'Residence Address', 'Residence Other', 'residenceCity',
       'residenceState', 'Residence City & State', 'residencePhone',
       'businessAddress1', 'businessAddress2', 'Business Address',
       'Business Other', 'businessCity', 'businessState',
       'Business City & State', 'businessPhone', 'ledger', 'link',
       'Ledger Link', 'Page', 'pdfFileName', 'symbolExists', 'sNumber',
       'sErased', 'Notes & Remarks', 'Column 29'],
      dtype='object')

In [9]:
kkkfull['Residence City & State'].value_counts()

Residence City & State
Denver, CO*          15003
Aurora, CO*            162
Aurora, CO             101
Edgewater, CO           40
Littleton, CO           16
                     ...
Port Arthur, TX          1
Utleyville, CO           1
Idaho Springs, CO        1
Las Animas, CO           1
Fort Logan, CO           1
Name: count, Length: 177, dtype: int64

In [10]:
citystate=kkkfull['Residence City & State'].value_counts()

In [17]:
kkkfull.dtypes

itemID                     object
Number                    float64
fullName                   object
Prefix                     object
Last Name                  object
First Name                 object
Middle Name                object
Suffix                     object
residenceAddress1          object
residenceAddress2          object
Residence Address          object
Residence Other            object
residenceCity              object
residenceState             object
Residence City & State     object
residencePhone             object
businessAddress1           object
businessAddress2           object
Business Address           object
Business Other             object
businessCity               object
businessState              object
Business City & State      object
businessPhone              object
ledger                     object
link                       object
Ledger Link                object
Page                        int64
pdfFileName                object
symbolExists                 bool
sNumber                      bool
sErased                      bool
Notes & Remarks            object
Column 29                  object
dtype: object

In [19]:
kkkfull.groupby('Residence City & State')